# network-environment.yaml
parameter_defaults:
  # Gateway router for the external network
  ExternalInterfaceDefaultRoute: 10.0.0.1
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.0.2.1
  ControlPlaneSubnetCidr: "24"
  # Generally the IP of the Undercloud
  EC2MetadataIp: 192.0.2.1
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["192.168.122.1"]
  # Customize the VLAN IDs to match the local environment
  #ExternalNetworkVlanID: 10
  #InternalApiNetworkVlanID: 20
  #StorageNetworkVlanID: 30
  #StorageMgmtNetworkVlanID: 40
  #TenantNetworkVlanID: 50
  # Set to empty string to enable multiple external networks or VLANs
  NeutronExternalNetworkBridge: "''"
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  BondInterfaceOvsOptions: "mode=active-backup"

